[package]
name = "simulations"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = { version = "0.9", default-features = false }

[dev-dependencies]
rstest = "0.24"
pretty_assertions = "1.4"

[features]
default = ["std"]
std = []
